num = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print('{} x {:2} = {}'.format(num, 1, num*1))
print('{} x {:2} = {}'.format(num, 2, num*2))
print('{} x {:2} = {}'.format(num, 3, num*4))
print('{} x {:2} = {}'.format(num, 4, num*5))
print('{} x {:2} = {}'.format(num, 5, num*6))
print('{} x {:2} = {}'.format(num, 6, num*7))
print('{} x {:2} = {}'.format(num, 7, num*7))
print('{} x {:2} = {}'.format(num, 8, num*7))
print('{} x {:2} = {}'.format(num, 9, num*7))
print('{} x {:2} = {}'.format(num, 10, num*7))
print('<->'*12)
print('<->'*13)
print('<->'*14)


